TBL_DOH_HIT: equ 0xe505
;
TBL_DOH_HIT_IDX_DOH_BEEN_HIT: equ 0  ; 1 when Doh is hit
TBL_DOH_HIT_IDX_HIT_CYCLE_NUM: equ 1
TBL_DOH_HIT_IDX_COLOR: equ 2

; ToDo
DOH_H_IT_2: equ 0xe2b9   ; 1 when Doh is hit

DOH_TABLE: equ 0xe50d
;
DOH_TABLE_IDX_DEFEATED: equ 0
DOH_TABLE_IDX_POSTMORTEN_ACTION: equ 1
DOH_TABLE_IDX_ROW_DELAY: equ 2
DOH_TABLE_IDX_ROW: equ 3
DOH_TABLE_IDX_DELAY_BEFORE_ENDING: equ 4



DOH_BULLETS_TABLE: equ 0xe563
;
DOH_BULLETS_ACTIVE: equ 0
DOH_BULLETS_TABLE_IDX_FOLLOW_VAUS: equ 1
DOH_BULLETS_TABLE_IDX_SKEWNESS: equ 2
DOH_BULLETS_TABLE_IDX_SKEWNESS_COUNTER: equ 3
;3; e566


DOH_NUM_ACTIVE_BULLETS: equ 0xe51a

DOH_NEW_BULLET_COUNTER: equ 0xe581

DOH_RECEIVED_HITS: equ 0xe5b3



DOH_CAN_THROW_BULLETS: equ 0xe578
DOH_THROW_BULLETS_COUNTER: equ 0xe579



DOH_NUM_COLS: equ 8
DOH_NUM_ROWS: equ 12

DOH_ROW_DRAW_COUNTER: equ 0xe56f
