DOH_IS_FIRING: equ 0xe50d

DOH_HIT: equ 0xe505     ; 1 when Doh is hit
DOH_HIT_2: equ 0xe2b9   ; 1 when Doh is hit

DOH_TABLE: equ 0xe50d
;
DOH_TABLE_IDX_DEFEATED: equ 0
DOH_TABLE_IDX_DELAY_COUNTER: equ 1
DOH_TABLE_IDX_COLOR: equ 2



DOH_BULLETS_TABLE: equ 0xe563
;
DOH_BULLETS_ACTIVE: equ 0
DOH_BULLETS_TABLE_IDX_X: equ 1


DOH_NUM_ACTIVE_BULLETS: equ 0xe51a


DOH_RECEIVED_HITS: equ 0xe5b3


DOH_CAN_THROW_BULLETS: equ 0xe578
DOH_THROW_BULLETS_COUNTER: equ 0xe579



DOH_NUM_COLS: equ 8
DOH_NUM_ROWS: equ 12

DOH_ROW_DRAW_COUNTER: equ 0xe56f
