;This table controls the doors
DOOR_TABLE: equ 0xe570
DOOR_TABLE_LEN: equ 6
;
DOOR_TABLE_IDX_ACTIVE: equ 0
DOOR_TABLE_IDX_DOOR: equ 1
DOOR_TABLE_IDX_COUNTER: equ 3
DOOR_TABLE_IDX_DOOR_OPEN_COUNTER: equ 4
