SOUND_BALL_BOUNCES_ON_VAUS: equ 1
SOUND_BRICK_DESTROYED: equ 2
SOUND_HARD_BRICK_HIT: equ 3
SOUND_PAUSE: equ 5
SOUND_VAUS_FIRING: equ 6
SOUND_VAUS_DESTROYED: equ 7
SOUND_DOH_HIT: equ 8
SOUND_DOH_DEFEATED: equ 9
SOUND_VAUS_INCREASES_SIZE: equ 10 ; 11
SOUND_VAUS_GOES_THROUGH_PORTAL: equ 12 ; 13
;
SOUND_START_MUSIC: equ 195
SOUND_LEVEL_START: equ 196
SOUND_LIFE: equ 197
SOUND_GAME_OVER: equ 198
SOUND_GAME_ENDING: equ 199
SOUND_DOH_APPEARS: equ 200
