SPR_PARAMS_LEN: equ 4

SPR_PARAMS_BASE: equ 0xe0cd

; Sprite parameter tables: (Y, X) position, sprite pattern number, and color

; Indices
SPR_PARAMS_IDX_Y: equ 0
SPR_PARAMS_IDX_X: equ 1
SPR_PARAMS_IDX_PATTERN_NUM: equ 2
SPR_PARAMS_IDX_COLOR: equ 3

; Falling capsules
FALLING_CAPSULE_SPR_PARAMS: equ SPR_PARAMS_BASE - 1*SPR_PARAMS_LEN ; Weird, it uses one position before the start

; Laser sprites
LASER1_SPR_PARAMS: equ SPR_PARAMS_BASE + 7*SPR_PARAMS_LEN
LASER2_SPR_PARAMS: equ SPR_PARAMS_BASE + 8*SPR_PARAMS_LEN
LASER3_SPR_PARAMS: equ SPR_PARAMS_BASE + 9*SPR_PARAMS_LEN

SPR_13_SPR_PARAMS: equ SPR_PARAMS_BASE + 13*SPR_PARAMS_LEN ; 0xe101

SPR_16_SPR_PARAMS: equ SPR_PARAMS_BASE + 16*SPR_PARAMS_LEN


; Ball sprite parameters
BALL1_SPR_PARAMS: equ SPR_PARAMS_BASE + 10*SPR_PARAMS_LEN; 0xe0f5
BALL2_SPR_PARAMS: equ SPR_PARAMS_BASE + 11*SPR_PARAMS_LEN
BALL3_SPR_PARAMS: equ SPR_PARAMS_BASE + 12*SPR_PARAMS_LEN
